export const Actiontypes={
    SET_PRODUCTS:"SET_PRODUCTS",
    SLECTED_PRODUCT: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCT:"REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCREMENT_QUANTITY: "INCREMENT_QUANTITY",
    DECREMENT_QUANTITY:"DECREMENT_QUANTITY",
    DISPLAY_USERNAME:"DISPLAY_USERNAME",
    CART_UPDATION:"CART_UPDATION"
}